version: '3'
services:
  flask_bo:
    image: flask_bo
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=${DEBUG}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TEST_DB=${TEST_DB}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # network_mode: "host"
      

# volumes:
#   db:
#     driver: local
  