# version: '3'
# services:
#   flask_bo:
#     image: flask_bo
#     build:
#       context: .
#       dockerfile: Dockerfile
#     restart: always
#     # ports:
#     # - "5000:5000"
#     # env_file:
#     #   - .env
      
#   db:
#     image: postgres:16.2-alpine3.19
#     restart: always
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=flask_bo
#     volumes: 
#       - db:/var/lib/postgresql/data
  
#   redis:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - "6379:6379"
# volumes:
#   db:
#     driver: local
  