# name: CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       DB_HOST: ${{ secrets.DB_HOST }}
#       DB_USER: ${{ secrets.DB_USER }}
#       DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
#       TEST_DB_USER: ${{ secrets.TEST_DB_USER }}
#       TEST_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
#       DB_PORT: ${{ secrets.DB_PORT }}
#       DB_NAME: ${{ secrets.DB_NAME }}
#       SECRET_KEY: ${{ secrets.SECRET_KEY }}
#       DEBUG: ${{ secrets.DEBUG }}

#       REDIS_HOST: ${{ secrets.REDIS_HOST }}
#       REDIS_PORT: ${{ secrets.REDIS_PORT }}
#       REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#   # deploy:
#   #   needs: build
#   #   runs-on: ubuntu-latest

#   #   steps:
#   #     - name: Checkout code
#   #       uses: actions/checkout@v2

#   #     - name: Deploy to PythonAnywhere
#   #       run: |
#   #         git push https://hiddengem@ssh.pythonanywhere.com/hiddengem/hidden-gem-backend master
