name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            sudo chmod 777 /var/run/docker.sock
            cd /home/aqzaqz/coba/flask_rest_boilerplate
            git pull origin main
            docker stop flask_bo_container
            docker rm  flask_bo_container
            docker rmi flask_bo_images:latest
            docker build -t flask_bo_images:latest .
            docker run -d \
            -p 5000:5000 \
            -e DB_HOST=${{ secrets.SERVER_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DEBUG=${{ secrets.DEBUG }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e TEST_DB=${{ secrets.TEST_DB }} \
            -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
            -e FLASK_DEBUG=${{ secrets.FLASK_DEBUG }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }}\
            -e REDIS_PASSWORD= ${{ secrets.REDIS_PASSWORD }} \
            --name flask_bo_container \
            flask_bo_images